const MutationTypes = { };

MutationTypes.TOGGLE_DRAWER = 'TOGGLE_DRAWER';

MutationTypes.SET_VARIANTS = 'SET_VARIANTS';
MutationTypes.SET_VARIANT_MAP = 'SET_VARIANT_MAP';

MutationTypes.SET_CURRENT_GAME = 'SET_CURRENT_GAME';
MutationTypes.SET_CURRENT_GAME_PHASES = 'SET_CURRENT_GAME_PHASES';
MutationTypes.SET_CURRENT_GAME_ORDERS = 'SET_CURRENT_GAME_ORDERS';
MutationTypes.SET_CURRENT_GAME_ORDINAL = 'SET_CURRENT_GAME_ORDINAL';

export default MutationTypes;
